build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
              override:
                - php-scrutinizer-run
                - js-scrutinizer-run

    environment:
      php: 8.0.0

filter:
    excluded_paths:
      - 'js/3rdParty/*'
      - 'vendor/*'
      - 'sample_data/*'
      - 'translationfiles/*'

imports:
    - javascript
    - php
